#!/bin/bash
set -ex

# BASEDIR is the location of your git checkout
BASEDIR=/opt/crypto

cd ${BASEDIR}
rm -rf static
mkdir static
chown 9000:9000 static
chown -R 9000:9000 media_files
git reset --hard
git pull
docker-compose up --force-recreate --build
