# Generated by Django 3.2.8 on 2021-10-24 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Crypto Ticker used for querying from CoinMarketCap', max_length=10)),
                ('display_name', models.CharField(help_text='Used as the header when charting', max_length=64)),
                ('show_overall', models.BooleanField(default=False, help_text='Show overall value instead of current price')),
                ('show_chart', models.BooleanField(default=False, help_text='Show 7-day chart with price trend on Dashboard', verbose_name='Chart crypto')),
                ('enabled', models.BooleanField(default=True, help_text='Hides crypto from Dashboard and does not pull further information')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('buy_price', models.FloatField(blank=True, help_text='If no buy price is specified, it will be looked up on CoinMarketCap based on the buying timestamp')),
                ('bought_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='crypto.crypto')),
            ],
            options={
                'verbose_name': 'Purchase',
            },
        ),
        migrations.CreateModel(
            name='CryptoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('percent_day', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='24h Percentual Change')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='crypto.crypto')),
            ],
            options={
                'verbose_name': 'Price Data',
                'verbose_name_plural': 'Price Data',
                'get_latest_by': 'timestamp',
            },
        ),
    ]
