# Generated by Django 3.2.8 on 2021-10-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodata',
            name='currency',
            field=models.CharField(default='USD', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptodata',
            name='rank',
            field=models.PositiveIntegerField(default=1337),
            preserve_default=False,
        ),
    ]
