# Generated by Django 3.2.8 on 2021-10-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20211024_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptodata',
            old_name='currency',
            new_name='source_currency',
        ),
        migrations.RenameField(
            model_name='cryptodata',
            old_name='price',
            new_name='source_price',
        ),
        migrations.AddField(
            model_name='cryptodata',
            name='target_currency',
            field=models.CharField(default='EUR', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptodata',
            name='target_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
