# Generated by Django 3.2.8 on 2021-10-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20211024_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopurchases',
            name='buy_currency',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='cryptopurchases',
            name='buy_price',
            field=models.FloatField(blank=True, help_text='If no buy price is specified, it will be looked up on CoinMarketCap based on the buying timestamp (requires Advanced API plan)'),
        ),
    ]
