# Generated by Django 3.2.8 on 2021-10-24 11:38

import crypto.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20211024_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='image',
            field=models.ImageField(default='crypto/default.png', upload_to=crypto.utils.crypto_image_path),
        ),
        migrations.AlterField(
            model_name='cryptopurchases',
            name='buy_currency',
            field=models.CharField(max_length=4),
        ),
    ]
