# Generated by Django 3.2.8 on 2021-10-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_auto_20211024_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto',
            options={'ordering': ('order', 'symbol')},
        ),
        migrations.AddField(
            model_name='crypto',
            name='order',
            field=models.PositiveSmallIntegerField(default=999),
        ),
    ]
