# Generated by Django 3.2.8 on 2021-10-31 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0007_auto_20211024_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopurchases',
            name='buy_price',
            field=models.FloatField(help_text='If no buy price is specified, it will be looked up on CoinMarketCap based on the buying timestamp (requires Advanced API plan)'),
        ),
        migrations.AlterField(
            model_name='cryptopurchases',
            name='target_currency',
            field=models.CharField(blank=True, help_text='Automatically converty buying price into localized-target price if left empty', max_length=4),
        ),
        migrations.AlterField(
            model_name='cryptopurchases',
            name='target_price',
            field=models.FloatField(blank=True, help_text='Automatically converts buying price into localized-target price if left empty'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(help_text='Price of crypto in target currency to surpass')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
            ],
            options={
                'verbose_name': 'Price Alert',
            },
        ),
    ]
